insert into emp(empno) values (2222)
insert into emp(empno,deptno) values (1111,40)
select * from emp

insert into emp(empno,deptno) values (1111,20)

BEGIN TRY
	INSERT EMP(EMPNO) VALUES(1234)
END TRY
BEGIN CATCH
PRINT @@ERROR
END CATCH


BEGIN TRY
	INSERT EMP(EMPNO) VALUES(1234)
END TRY
BEGIN CATCH
PRINT @@ERROR
PRINT ERROR_NUMBER()
END CATCH

BEGIN TRY
	INSERT EMP(EMPNO) VALUES(1234)
END TRY
BEGIN CATCH
--PRINT @@ERROR
PRINT ERROR_NUMBER()
PRINT ERROR_MESSAGE();
END CATCH


BEGIN TRY
	INSERT EMP(EMPNO) VALUES(1234)
END TRY
BEGIN CATCH
--PRINT @@ERROR
PRINT ERROR_NUMBER();
--PRINT ERROR_MESSAGE();
THROW
END CATCH


BEGIN TRY
	INSERT EMP(EMPNO) VALUES(1234)
END TRY
BEGIN CATCH
--PRINT @@ERROR
PRINT ERROR_NUMBER();
--PRINT ERROR_MESSAGE();
THROW 51000,'SORRY!!!  Couldnot add record since few data were missing. Please contact Admin',1
END CATCH


DECLARE @result INT;
BEGIN TRY
SET @result=1/0;
PRINT @result
END TRY
BEGIN CATCH
PRINT ERROR_MESSAGE() +' ' +
CAST(ERROR_NUMBER() AS VARCHAR)
END CATCH


DECLARE @result INT;
BEGIN TRY
SET @result=1/0;
PRINT @result
END TRY
PRINT 'I AM IN BETWEEN TRY AND CATCH SO ERROR WILL POP'
BEGIN CATCH
PRINT ERROR_MESSAGE() +' ' +
CAST(ERROR_NUMBER() AS VARCHAR)
END CATCH
