
SELECT E.ENAME, E.EMPNO,D.LOC,D.DEPTNO,D.LOC
FROM EMP E
JOIN
DEPT D
ON(E.DEPTNO = D.DEPTNO)
AND D.LOC = 'CHICAGO';

SELECT E.ENAME,E.EMPNO,D.LOC,D.DEPTNO
FROM EMP E
JOIN DEPT D
ON(E.DEPTNO=D.DEPTNO)
ORDER BY LOC;

SELECT E.ENAME,D.LOC
FROM EMP E
JOIN
DEPT D
ON(D.DEPTNO=E.DEPTNO)
ORDER BY LOC;

SELECT E.ENAME AS 'MANAGER',C.ENAME AS 'EMPLOYEE'
FROM EMP  C
JOIN
EMP E
ON(E.EMPNO=C.MGR)
AND E.HIREDATE>C.HIREDATE;

SELECT E.ENAME,D.DNAME
FROM EMP E
JOIN
DEPT D
ON(E.DEPTNO=D.DEPTNO);

SELECT E.EMPNO, E.ENAME,E.HIREDATE,J.STARTDATE,J.ENDDATE
FROM EMP E
JOIN JOBHIST J
ON E.HIREDATE BETWEEN J.STARTDATE AND ENDDATE;

SELECT E.ENAME,E.EMPNO,D.LOC,D.DEPTNO
FROM EMP E
JOIN DEPT D
ON(E.DEPTNO=D.DEPTNO);

SELECT e.EMPNO ,e.ENAME ,d.LOC
FROM EMP e  FULL OUTER JOIN  DEPT d
ON ( d.DEPTNO = e.DEPTNO )
WHERE  d.LOC = 'CHICAGO' ;

SELECT e.ENAME , d.LOC
FROM EMP e LEFT OUTER JOIN DEPT d
 ON(d.DEPTNO =E.DEPTNO)
ORDER BY d.LOC;

SELECT Manger.ENAME AS 'MANAGER', employee.ENAME AS 'EMPLOYEE'
FROM  EMP Manger FULL OUTER JOIN EMP employee
ON (Manger.EMPNO = employee.MGR)
where Manger.HIREDATE < employee.HIREDATE;

SELECT e.ENAME , d.DNAME
FROM EMP e JOIN DEPT d
ON( d.DEPTNO =E.DEPTNO);

SELECT e.ENAME , d.LOC
FROM EMP e JOIN DEPT d
ON( d.DEPTNO =E.DEPTNO);

SELECT e.ENAME, e.HIREDATE ,j.startdate ,j.enddate
FROM EMP e JOIN JOBHIST j
ON( e.HIREDATE BETWEEN j.startdate AND j.enddate);