SELECT JOB, SUM(SAL) SALESMANSAL
FROM EMP
GROUP BY JOB
HAVING JOB = 'SALESMAN';

SELECT DEPTNO, AVG(SAL) AVERAGE
FROM EMP
GROUP BY DEPTNO;

SELECT JOB,AVG(SAL)
FROM EMP
GROUP BY JOB
HAVING JOB = 'ANALYST';