SELECT 
E.ENAME,E.EMPNO,D.LOC,D.DEPTNO
FROM EMP E,DEPT D
WHERE E.DEPTNO=D.DEPTNO AND D.LOC = 'CHICAGO';

SELECT E.ENAME,D.LOC 
FROM EMP E,DEPT D
WHERE D.DEPTNO=E.DEPTNO ORDER BY LOC;

SELECT E.ENAME,E.EMPNO,D.LOC,D.DEPTNO
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY LOC;

SELECT EMP.ENAME,DEPT.DNAME
FROM EMP,DEPT;

SELECT E.EMPNO,E.ENAME,E.HIREDATE,J.STARTDATE,J.ENDDATE
FROM EMP E,JOBHIST J
WHERE E.HIREDATE BETWEEN J.STARTDATE AND J.ENDDATE;

SELECT E.ENAME,D.LOC
FROM EMP E,DEPT D
WHERE D.DEPTNO = E.DEPTNO;