SELECT EMPNO,COMM,DEPTNO,HIREDATE
FROM emp
UNION ALL
SELECT empno ,COMM,DEPTNO,enddate
FROM jobhist
ORDER BY HIREDATE DESC;Select empno
from emp
where comm is null and comm!=0
INTERSECT
SELECT EMPNO
FROM JOBHIST
WHERE COMM IS NOT NULL AND ENDDATE IS NOT NULL;SELECT EMPNO
FROM EMP
WHERE JOB='SALESMAN'
EXCEPT
SELECT EMPNO
FROM JOBHIST
WHERE JOB='SALESMAN' AND ENDDATE IS NOT NULL;

SELECT E.ENAME,E.EMPNO,D.DEPTNO,D.DNAME
FROM DEPT D
FULL OUTER JOIN
EMP E
ON(D.DEPTNO = E.DEPTNO)
WHERE D.DEPTNO IN (SELECT D.DEPTNO 
                   FROM DEPT D
				   UNION
				   SELECT E.DEPTNO
				   FROM EMP E)

